Exceptions thrown from the synchorous function crashs me
